# Generated by Django 4.1.2 on 2022-10-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MA', 'Math'), ('SP', 'Spanish'), ('GT', 'Guitar')], max_length=2)),
                ('classesPerWeek', models.IntegerField(choices=[('uno', '1'), ('dos', '2'), ('tres', '3'), ('cuatro', '4'), ('cinco', '5')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20, unique=True)),
                ('friends', models.ManyToManyField(blank=True, to='userLessons.user')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userLessons.lesson')),
            ],
        ),
    ]
