# Generated by Django 4.1.2 on 2022-10-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userLessons.user'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classesPerWeek',
            field=models.CharField(choices=[('uno', '1'), ('dos', '2'), ('tres', '3'), ('cuatro', '4'), ('cinco', '5')], default='uno', max_length=6),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(choices=[('MA', 'Math'), ('SP', 'Spanish'), ('GT', 'Guitar')], default='MA', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
