# Generated by Django 4.1.2 on 2022-10-17 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLessons', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classesPerWeek',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userLessons.user'),
        ),
    ]
